### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by walmat** [Nebulabots/cookie-harvester#1]
Things that need to be done:
- [ ] Authentication
  - Similar to how Ghost does theirs, we could just have a button that the user can click in Omega's settings dialog that sets up the communication. https://support.ghostaio.com/hc/en-us/articles/360034546152-How-to-use-install-the-Phantom-Google-Chrome-Extension-Manual-Cookie-Harvester-
- [ ] Ability to choose the site they want to harvest on from a dropdown
- [ ] Ability to paste in proxies to a textfield to be used
   - The extension would harvest on the chosen site using these proxies. We would have to figure out how to set a proxy in Chrome
- [ ] Create communication between the extension and Omega to transfer stored cookies after harvesting
- [ ] A way to generate human activity (mouse movements, keystrokes, etc.) without taking control of the user's mouse.

**Comment by walmat** [comment]
Here are the sites that we'll want to harvest on:
```js
const SITE_TO_URL = {
        /* US footsites */
        'footaction': 'https://www.footaction.com',
        'eastbay': 'https://www.eastbay.com',
        'footlocker': 'https://www.footlocker.com',
        'champssports': 'https://www.champssports.com',
        'footlockerca': 'https://www.footlocker.ca',
        'kidsfootlocker': 'https://www.kidsfootlocker.com',
        'converse': 'https://www.converse.com',
        /* eu */
        'footlockeruk': 'https://www.footlocker.co.uk',
        'footlockerno': 'https://www.footlocker.no',
        'footlockerse': 'https://www.footlocker.se',
        'footlockerdk': 'https://www.footlocker.dk',
        'footlockersg': 'https://www.footlocker.sg',
        'footlockermy': 'https://www.footlocker.my',
        'footlockerhk': 'https://www.footlocker.hk',
        'footlockerfr': 'https://www.footlocker.fr',
        'footlockerde': 'https://www.footlocker.de',
        'footlockerlu': 'https://www.footlocker.lu',
        'footlockerbe': 'https://www.footlocker.be',
        'footlockernl': 'https://www.footlocker.nl',
        'footlockerit': 'https://www.footlocker.it',
        'footlockeres': 'https://www.footlocker.es',
        /* Adidas sites */
        'adidas-us': 'https://www.adidas.com',
        'adidas-gb': 'https://www.adidas.co.uk',
        'adidas-fr': 'https://www.adidas.fr',
        'adidas-au': 'https://www.adidas.com.au',
        'adidas-de': 'https://www.adidas.de',
        'adidas-es': 'https://www.adidas.es',
        'adidas-it': 'https://www.adidas.it',
        'adidas-nz': 'https://www.adidas.co.nz',
        'adidas-mx': 'https://www.adidas.mx',
        'adidas-ru': 'https://www.adidas.ru',
        'adidas-se': 'https://www.adidas.se',
        'adidas-sg': 'https://www.adidas.com.sg',
        'adidas-at': 'https://www.adidas.at',
        'adidas-be': 'https://www.adidas.be',
        'adidas-br': 'https://www.adidas.com.br',
        'adidas-cz': 'https://www.adidas.cz',
        'adidas-dk': 'https://www.adidas.dk',
        'adidas-fi': 'https://www.adidas.fi',
        'adidas-ph': 'https://www.adidas.com.ph',
        'adidas-pl': 'https://www.adidas.pl',
        'adidas-my': 'https://www.adidas.com.my',
        'adidas-sk': 'https://www.adidas.sk',
        'adidas-ch': 'https://www.adidas.ch',
        'adidas-ca': 'https://www.adidas.ca',
        'adidas-nl': 'https://www.adidas.nl',
        'yeezysupply': 'https://www.yeezysupply.com',
        /* Dicks */
        'dicks': 'https://www.dickssportinggoods.com',
        /* Mesh */
        'size': 'https://www.size.co.uk',
        'footpatrol': 'https://www.footpatrol.com',
        // 'jdsports': 'https://www.jdsports.co.uk',
        // 'thehipstore': 'https://www.thehipstore.co.uk',
        /* FNL */
        'finishline': 'https://www.finishline.com',
        'jdsports-us': 'https://www.jdsports.com',
    }
```

**Comment by sibelius** [comment]
baseline
![image](https://user-images.githubusercontent.com/2005841/83352697-d8850300-a323-11ea-8b87-db33f0867b10.png)
![image](https://user-images.githubusercontent.com/2005841/83352701-e044a780-a323-11ea-9d32-6b3e76f68457.png)

https://support.ghostaio.com/hc/en-us/articles/360034546152-How-to-use-install-the-Phantom-Google-Chrome-Extension-Manual-Cookie-Harvester-

**Comment by sibelius** [comment]
proxy format

ip:port:user:pass

**Comment by sibelius** [comment]
chrome proxy set https://github.com/henices/Chrome-proxy-helper

**Comment by sibelius** [comment]
chrome extensions examples https://github.com/mdn/webextensions-examples

**Comment by sibelius** [comment]
https://github.com/incu6us/proxy-chrome-extension/blob/master/js/background.js

**Comment by sibelius** [comment]
webRequest api https://developer.chrome.com/extensions/webRequest
